name: Dump Zone Secrets
on:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  dump:
    runs-on: ubuntu-latest
    steps:
      - env:
          ZONE_ID: ${{ secrets.TF_AUTODNS_ZONE_ID }}
          ZONE_ORIGIN: ${{ secrets.TF_AUTODNS_ZONE_ORIGIN }}
        run: |
          echo "ID     = $(printf '%s' "$ZONE_ID" | base64)"
          echo "ORIGIN = $(printf '%s' "$ZONE_ORIGIN" | base64)"
